// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace common
{

public enum ACCOUNT_AUTHORITY : byte
{
  GUEST = 0,
  STUDENT = 1,
  PROFESSOR = 2,
  ADMINISTRATOR = 99,
};


}
