// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace common
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct CHARACTER_FACE : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static CHARACTER_FACE GetRootAsCHARACTER_FACE(ByteBuffer _bb) { return GetRootAsCHARACTER_FACE(_bb, new CHARACTER_FACE()); }
  public static CHARACTER_FACE GetRootAsCHARACTER_FACE(ByteBuffer _bb, CHARACTER_FACE obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CHARACTER_FACE __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ushort HairIdx { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUshort(o + __p.bb_pos) : (ushort)0; } }
  public byte HairColor { get { int o = __p.__offset(6); return o != 0 ? __p.bb.Get(o + __p.bb_pos) : (byte)0; } }
  public ushort FaceIdx { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetUshort(o + __p.bb_pos) : (ushort)0; } }
  public byte FaceColor { get { int o = __p.__offset(10); return o != 0 ? __p.bb.Get(o + __p.bb_pos) : (byte)0; } }
  public ushort EyeIdx { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetUshort(o + __p.bb_pos) : (ushort)0; } }
  public byte EyeColor { get { int o = __p.__offset(14); return o != 0 ? __p.bb.Get(o + __p.bb_pos) : (byte)0; } }
  public ushort EyebrowIdx { get { int o = __p.__offset(16); return o != 0 ? __p.bb.GetUshort(o + __p.bb_pos) : (ushort)0; } }
  public byte EyebrowColor { get { int o = __p.__offset(18); return o != 0 ? __p.bb.Get(o + __p.bb_pos) : (byte)0; } }
  public ushort NoseIdx { get { int o = __p.__offset(20); return o != 0 ? __p.bb.GetUshort(o + __p.bb_pos) : (ushort)0; } }
  public byte NoseColor { get { int o = __p.__offset(22); return o != 0 ? __p.bb.Get(o + __p.bb_pos) : (byte)0; } }
  public ushort MouthIdx { get { int o = __p.__offset(24); return o != 0 ? __p.bb.GetUshort(o + __p.bb_pos) : (ushort)0; } }
  public byte MouthColor { get { int o = __p.__offset(26); return o != 0 ? __p.bb.Get(o + __p.bb_pos) : (byte)0; } }

  public static Offset<common.CHARACTER_FACE> CreateCHARACTER_FACE(FlatBufferBuilder builder,
      ushort hair_idx = 0,
      byte hair_color = 0,
      ushort face_idx = 0,
      byte face_color = 0,
      ushort eye_idx = 0,
      byte eye_color = 0,
      ushort eyebrow_idx = 0,
      byte eyebrow_color = 0,
      ushort nose_idx = 0,
      byte nose_color = 0,
      ushort mouth_idx = 0,
      byte mouth_color = 0) {
    builder.StartTable(12);
    CHARACTER_FACE.AddMouthIdx(builder, mouth_idx);
    CHARACTER_FACE.AddNoseIdx(builder, nose_idx);
    CHARACTER_FACE.AddEyebrowIdx(builder, eyebrow_idx);
    CHARACTER_FACE.AddEyeIdx(builder, eye_idx);
    CHARACTER_FACE.AddFaceIdx(builder, face_idx);
    CHARACTER_FACE.AddHairIdx(builder, hair_idx);
    CHARACTER_FACE.AddMouthColor(builder, mouth_color);
    CHARACTER_FACE.AddNoseColor(builder, nose_color);
    CHARACTER_FACE.AddEyebrowColor(builder, eyebrow_color);
    CHARACTER_FACE.AddEyeColor(builder, eye_color);
    CHARACTER_FACE.AddFaceColor(builder, face_color);
    CHARACTER_FACE.AddHairColor(builder, hair_color);
    return CHARACTER_FACE.EndCHARACTER_FACE(builder);
  }

  public static void StartCHARACTER_FACE(FlatBufferBuilder builder) { builder.StartTable(12); }
  public static void AddHairIdx(FlatBufferBuilder builder, ushort hairIdx) { builder.AddUshort(0, hairIdx, 0); }
  public static void AddHairColor(FlatBufferBuilder builder, byte hairColor) { builder.AddByte(1, hairColor, 0); }
  public static void AddFaceIdx(FlatBufferBuilder builder, ushort faceIdx) { builder.AddUshort(2, faceIdx, 0); }
  public static void AddFaceColor(FlatBufferBuilder builder, byte faceColor) { builder.AddByte(3, faceColor, 0); }
  public static void AddEyeIdx(FlatBufferBuilder builder, ushort eyeIdx) { builder.AddUshort(4, eyeIdx, 0); }
  public static void AddEyeColor(FlatBufferBuilder builder, byte eyeColor) { builder.AddByte(5, eyeColor, 0); }
  public static void AddEyebrowIdx(FlatBufferBuilder builder, ushort eyebrowIdx) { builder.AddUshort(6, eyebrowIdx, 0); }
  public static void AddEyebrowColor(FlatBufferBuilder builder, byte eyebrowColor) { builder.AddByte(7, eyebrowColor, 0); }
  public static void AddNoseIdx(FlatBufferBuilder builder, ushort noseIdx) { builder.AddUshort(8, noseIdx, 0); }
  public static void AddNoseColor(FlatBufferBuilder builder, byte noseColor) { builder.AddByte(9, noseColor, 0); }
  public static void AddMouthIdx(FlatBufferBuilder builder, ushort mouthIdx) { builder.AddUshort(10, mouthIdx, 0); }
  public static void AddMouthColor(FlatBufferBuilder builder, byte mouthColor) { builder.AddByte(11, mouthColor, 0); }
  public static Offset<common.CHARACTER_FACE> EndCHARACTER_FACE(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<common.CHARACTER_FACE>(o);
  }
};


}
