// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace common
{

public enum CHARACTER_TYPE : byte
{
  NONE = 0,
  MAN = 1,
  WOMAN = 2,
};


}
