// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace protocol
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct CHARACTER_INFO_C2S : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static CHARACTER_INFO_C2S GetRootAsCHARACTER_INFO_C2S(ByteBuffer _bb) { return GetRootAsCHARACTER_INFO_C2S(_bb, new CHARACTER_INFO_C2S()); }
  public static CHARACTER_INFO_C2S GetRootAsCHARACTER_INFO_C2S(ByteBuffer _bb, CHARACTER_INFO_C2S obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CHARACTER_INFO_C2S __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartCHARACTER_INFO_C2S(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<protocol.CHARACTER_INFO_C2S> EndCHARACTER_INFO_C2S(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<protocol.CHARACTER_INFO_C2S>(o);
  }
};


}
